apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: adjudicationorders.securemas.io
spec:
  group: securemas.io
  scope: Namespaced
  names:
    plural: adjudicationorders
    singular: adjudicationorder
    kind: AdjudicationOrder
    shortNames:
      - ajb
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                orderId:
                  type: string
                eventId:
                  type: string
                taskId:
                  type: string
                agentId:
                  type: string
                actions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        enum:
                          - RESTRICT_EGRESS
                          - SUSPEND_AGENT
                          - REVOKE_TOKEN
                          - QUARANTINE_POD
                      params:
                        type: object
                        additionalProperties:
                          type: string
                reason:
                  type: string
                issuedAt:
                  type: string
                  format: date-time
                signature:
                  type: object
                  properties:
                    algorithm:
                      type: string
                      enum:
                        - hmac-sha256
                        - ed25519
                    value:
                      type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - PENDING
                    - VERIFIED
                    - EXECUTING
                    - EXECUTED
                    - REJECTED
                executionReceiptRef:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - "Unknown"
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
