apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: executionreceipts.securemas.io
spec:
  group: securemas.io
  scope: Namespaced
  names:
    plural: executionreceipts
    singular: executionreceipt
    kind: ExecutionReceipt
    shortNames:
      - exreceipt
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                receiptId:
                  type: string
                orderId:
                  type: string
                eventId:
                  type: string
                taskId:
                  type: string
                agentId:
                  type: string
                executedAt:
                  type: string
                  format: date-time
                results:
                  type: array
                  items:
                    type: object
                    properties:
                      action:
                        type: string
                      status:
                        type: string
                        enum:
                          - SUCCESS
                          - FAIL
                      message:
                        type: string
                auditLogRef:
                  type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - "Unknown"
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
