apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: securityevents.securemas.io
spec:
  group: securemas.io
  scope: Namespaced
  names:
    plural: securityevents
    singular: securityevent
    kind: SecurityEvent
    shortNames:
      - secevent
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                eventId:
                  type: string
                taskId:
                  type: string
                agentId:
                  type: string
                type:
                  type: string
                  enum:
                    - compute
                    - network
                    - policy
                    - behavior
                severity:
                  type: string
                  enum:
                    - low
                    - medium
                    - high
                confidence:
                  type: number
                  minimum: 0
                  maximum: 1
                summary:
                  type: string
                evidenceRefs:
                  type: array
                  items:
                    type: string
                recommendedActions:
                  type: array
                  items:
                    type: string
                detectedAt:
                  type: string
                  format: date-time
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - NEW
                    - INVESTIGATING
                    - INVESTIGATED
                    - ADJUDICATED
                    - EXECUTED
                    - DISMISSED
                adjudicationOrderRef:
                  type: string
                executionReceiptRef:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - "Unknown"
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
