apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tasksecurityprofiles.securemas.io
spec:
  group: securemas.io
  scope: Namespaced
  names:
    plural: tasksecurityprofiles
    singular: tasksecurityprofile
    kind: TaskSecurityProfile
    shortNames:
      - tsp
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                profileId:
                  type: string
                datasets:
                  type: object
                  properties:
                    allow:
                      type: array
                      items:
                        type: string
                tools:
                  type: object
                  properties:
                    allow:
                      type: array
                      items:
                        type: string
                egress:
                  type: object
                  properties:
                    allowHosts:
                      type: array
                      items:
                        type: string
                output:
                  type: object
                  properties:
                    redactPatterns:
                      type: array
                      items:
                        type: string
                    maxTokens:
                      type: integer
                      minimum: 0
                isolation:
                  type: object
                  properties:
                    mode:
                      type: string
                      enum:
                        - standard
                        - tee
                    attestationRequired:
                      type: boolean
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - "Unknown"
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
