apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tasks.securemas.io
spec:
  group: securemas.io
  scope: Namespaced
  names:
    plural: tasks
    singular: task
    kind: Task
    shortNames:
      - smtask
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                taskId:
                  type: string
                tenantId:
                  type: string
                graphRef:
                  type: string
                input:
                  type: object
                  properties:
                    params:
                      type: object
                      additionalProperties:
                        type: string
                policyBundleRef:
                  type: string
                securityProfileRef:
                  type: string
                checkpoint:
                  type: object
                  properties:
                    uri:
                      type: string
                    mode:
                      type: string
                      enum:
                        - readwrite
                        - readonly
                scheduling:
                  type: object
                  properties:
                    preferredAgents:
                      type: array
                      items:
                        type: string
                    allowFallback:
                      type: boolean
                timeouts:
                  type: object
                  properties:
                    executionSeconds:
                      type: integer
                      minimum: 1
                annotations:
                  type: object
                  properties:
                    riskLevel:
                      type: string
                      enum:
                        - low
                        - medium
                        - high
                    dataClassification:
                      type: string
                      enum:
                        - public
                        - internal
                        - restricted
                        - secret
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - INIT
                    - COMPLIANCE_REVIEW
                    - READY
                    - RUNNING
                    - DEGRADED
                    - SUSPENDED
                    - COMPLETED
                    - FAILED
                currentAgentId:
                  type: string
                lastCheckpoint:
                  type: object
                  properties:
                    uri:
                      type: string
                    time:
                      type: string
                      format: date-time
                attempts:
                  type: integer
                  minimum: 0
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - "Unknown"
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                audit:
                  type: object
                  properties:
                    logRef:
                      type: string
